[package]
name = "sql-fmt"
version = "0.1.0"
edition = "2021"
description = "Format SQL files with perfect grid alignment"
authors = ["Tristan J. Poland"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
glob = "0.3"
regex = "1.10"